#!/usr/bin/env bash
#Script that displays the content of the file /etc/passwd



file_path="/etc/passwd"

while IFS=: read -r username _ uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home directory: $home"
    echo "------------------------"
done < "$file_path"
